# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev
    env:
      MY_SECRET: ${{ secrets.TEST_VARIABLE }}
      MY_VAR: ${{ vars.MY_CUSTOM_VARIABLE }}
    concurrency:
        group: ${{ github.workflow }}-${{ github.ref }}
        cancel-in-progress: true
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Wait for 40 seconds
        uses: actions/github-script@v6
        with:
          script: |
            const wait = (ms) => new Promise(resolve => setTimeout(resolve, ms));
            await wait(40000);
      - name: Continue with other steps
        run: echo "Done waiting!"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Check if secret is empty
        run: echo $MY_SECRET

      - name: Check if var is empty
        run: echo $MY_VAR
        

